Controllers/TransaccionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using crudNomina.Data;

namespace crudNomina.Controllers
{
    public class TransaccionesController : Controller
    {
        private readonly NominaContext _context;

        public TransaccionesController(NominaContext context)
        {
            _context = context;
        }
       
        [HttpPost]
        public IActionResult Index([FromForm] DateTime? startDate, [FromForm] DateTime?  endDate)
        {
            var transaccions = _context.Transaccions
                .Include(t => t.IdDeduccionNavigation)
                .Include(t => t.IdEmpleadoNavigation)
                .Include(t => t.IdIngresoNavigation)
                .Where(t => (!startDate.HasValue || t.Fecha >= startDate) && (!endDate.HasValue || t.Fecha <= endDate)).ToList();

            return View(transaccions);
        }
        // GET: Transacciones
        public async Task<IActionResult> Index()
        {
            var nominaContext = _context.Transaccions.Include(t => t.IdDeduccionNavigation).Include(t => t.IdEmpleadoNavigation).Include(t => t.IdIngresoNavigation);
            return View(await nominaContext.ToListAsync());
        }

        // GET: Transacciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }   

            var transaccion = await _context.Transaccions
                .Include(t => t.IdDeduccionNavigation)
                .Include(t => t.IdEmpleadoNavigation)
                .Include(t => t.IdIngresoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaccion == null)
            {
                return NotFound();
            }

            return View(transaccion);
        }

        // GET: Transacciones/Create
        public IActionResult Create()
        {
            ViewData["IdDeduccion"] = new SelectList(_context.Deduccions, "Id", "Nombre");
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "Id", "Nombre");
            ViewData["IdIngreso"] = new SelectList(_context.Ingresos, "Id", "Nombre");
            return View();
        }

        // POST: Transacciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdEmpleado,IdDeduccion,IdIngreso,TipoTransaccion,Fecha,Monto,Estado")] Transaccion transaccion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaccion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDeduccion"] = new SelectList(_context.Deduccions, "Id", "Nombre", transaccion.IdDeduccion);
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "Id", "Nombre", transaccion.IdEmpleado);
            ViewData["IdIngreso"] = new SelectList(_context.Ingresos, "Id", "Nombre", transaccion.IdIngreso);
            return View(transaccion);
        }

        // GET: Transacciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaccion = await _context.Transaccions.FindAsync(id);
            if (transaccion == null)
            {
                return NotFound();
            }
            ViewData["IdDeduccion"] = new SelectList(_context.Deduccions, "Id", "Nombre", transaccion.IdDeduccion);
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "Id", "Nombre", transaccion.IdEmpleado);
            ViewData["IdIngreso"] = new SelectList(_context.Ingresos, "Id", "Nombre", transaccion.IdIngreso);
            return View(transaccion);
        }

        // POST: Transacciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdEmpleado,IdDeduccion,IdIngreso,TipoTransaccion,Fecha,Monto,Estado")] Transaccion transaccion)
        {
            if (id != transaccion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaccion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransaccionExists(transaccion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDeduccion"] = new SelectList(_context.Deduccions, "Id", "Nombre", transaccion.IdDeduccion);
            ViewData["IdEmpleado"] = new SelectList(_context.Empleados, "Id", "Nombre", transaccion.IdEmpleado);
            ViewData["IdIngreso"] = new SelectList(_context.Ingresos, "Id", "Nombre", transaccion.IdIngreso);
            return View(transaccion);
        }

        // GET: Transacciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaccion = await _context.Transaccions
                .Include(t => t.IdDeduccionNavigation)
                .Include(t => t.IdEmpleadoNavigation)
                .Include(t => t.IdIngresoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaccion == null)
            {
                return NotFound();
            }

            return View(transaccion);
        }

        // POST: Transacciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaccion = await _context.Transaccions.FindAsync(id);
            _context.Transaccions.Remove(transaccion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransaccionExists(int id)
        {
            return _context.Transaccions.Any(e => e.Id == id);
        }
    }
}

Views/Transacciones/Create.cshtml
@model crudNomina.Data.Transaccion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Transaccion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdEmpleado" class="control-label"></label>
                <select asp-for="IdEmpleado" class ="form-control" asp-items="ViewBag.IdEmpleado"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdDeduccion" class="control-label"></label>
                <select asp-for="IdDeduccion" class ="form-control" asp-items="ViewBag.IdDeduccion"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdIngreso" class="control-label"></label>
                <select asp-for="IdIngreso" class ="form-control" asp-items="ViewBag.IdIngreso"></select>
            </div>
            <div class="form-group">
                <label asp-for="TipoTransaccion" class="control-label"></label>
                <input asp-for="TipoTransaccion" class="form-control" />
                <span asp-validation-for="TipoTransaccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Transacciones/Delete.cshtml
@model crudNomina.Data.Transaccion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h4>Transaccion</h4>
<hr />
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaccion</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoTransaccion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoTransaccion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdDeduccionNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdDeduccionNavigation.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpleadoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEmpleadoNavigation.Cedula)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdIngresoNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdIngresoNavigation.Nombre)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Transacciones/Details.cshtml
@model crudNomina.Data.Transaccion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Transaccion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoTransaccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoTransaccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Monto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Monto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdDeduccionNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdDeduccionNavigation.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpleadoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpleadoNavigation.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdIngresoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdIngresoNavigation.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Transacciones/Edit.cshtml
@model crudNomina.Data.Transaccion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Transaccion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdEmpleado" class="control-label"></label>
                <select asp-for="IdEmpleado" class="form-control" asp-items="ViewBag.IdEmpleado"></select>
                <span asp-validation-for="IdEmpleado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDeduccion" class="control-label"></label>
                <select asp-for="IdDeduccion" class="form-control" asp-items="ViewBag.IdDeduccion"></select>
                <span asp-validation-for="IdDeduccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdIngreso" class="control-label"></label>
                <select asp-for="IdIngreso" class="form-control" asp-items="ViewBag.IdIngreso"></select>
                <span asp-validation-for="IdIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoTransaccion" class="control-label"></label>
                <input asp-for="TipoTransaccion" class="form-control" />
                <span asp-validation-for="TipoTransaccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Monto" class="control-label"></label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Transacciones/Index.cshtml
@model IEnumerable<crudNomina.Data.Transaccion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<h4>Transaccion</h4>
<hr />

<form id="formDate" asp-controller="Transacciones" method="post" asp-action="Index" class="d-flex justify-content-between ">
    <div class="col-2"><a asp-action="Create">Create New</a></div>
    <div class="d-flex justify-content-around ">
        <div class="col-3 ">
            <label for="startDate">Fecha Desde:</label>
            <input class="form-control-sm" type="datetime-local" id="startDate" name="startDate">

        </div>
        <div class="col-3">
            <label for="endDate">Fecha Hasta:</label>
            <input class="form-control-sm" type="datetime-local" id="endDate" name="endDate">

        </div>
    </div>

    <div class="col-2">
        <button id="filtrar" class="btn btn-outline-primary" type="submit">Filtrar</button>
    </div>



</form>
<div class="col-2 d-flex align-content-end" >
    <button id="Contabilizar" class="btn btn-success">Contabilizar</button>
</div>
<table class="table mt-3">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TipoTransaccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEmpleadoNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdDeduccionNavigation)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.IdIngresoNavigation)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Monto)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoTransaccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEmpleadoNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdDeduccionNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdIngresoNavigation.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Monto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fecha)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
 
</table>